get:
  tags: [admin]
  summary: List templates for composer (admin only)
  description: Returns all templates for the composer. Requires admin privileges.
  responses:
    "200":
      description: ""
      content:
        application/json:
          schema:
            type: object
            properties:
              templates:
                type: array
                items:
                  type: object
                  properties:
                    id: { type: string }
                    title: { type: string }
                    createdAt: { type: number }
                    updatedAt: { type: number }
                    fields:
                      type: array
                      items:
                        type: object
                        properties:
                          key: { type: string }
                          label: { type: string }
                          type: { type: string }
                          required: { type: boolean }
